### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by tex** [222464/NeoRL-CPU#1]
runnig cmake . && make gives me this

In file included from /usr/include/c++/5.2.0/random:35:0,
                 from /home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.h:4,
                 from /home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.cpp:1:
/usr/include/c++/5.2.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.cpp:1:0:
/home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.h:65:272: error: ‘std::mt19937’ has not been declared
 dius, int recurrentRadius, int lateralRadius, float initMinWeight, float initMaxWeight, float initMinInhibition, float initMaxInhibition, float initThreshold, std::mt19937 &ge
                                                                                                                                                                     ^
/home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.h:67:80: error: ‘std::mt19937’ has not been declared
   void activate(int settleIter, int measureIter, float leak, float noise, std::mt19937 &generator);
                                                                                ^
/home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.h:68:146: error: ‘std::mt19937’ has not been declared
   void inhibit(const std::vector<float> &excitations, int settleIter, int measureIter, float leak, float noise, std::vector<float> &states, std::mt19937 &generator);
                                                                                                                                                  ^
In file included from /home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.cpp:1:0:
/home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.h: In static member function ‘static float neo::SparseCoder::sigmoid(float)’:
/home/milan/tmp/NeoRL-CPU/NeoRL-CPU/source/neo/SparseCoder.h:62:26: error: ‘exp’ is not a member of ‘std’
    return 1.0f / (1.0f + std::exp(-x));
                          ^
/

**Comment by 222464** [comment]
Hello,

did you enable C++11 support?

**Comment by tex** [comment]
How? I assumed that cmake should do it based on what is in CMakeFileList.txt.

**Comment by 222464** [comment]
Can you pull the latest? It should have this fixed in the CMakeLists.txt.
Let me know if it works!

**Comment by tex** [comment]
Yes, it is fixed. Thanks!
